import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { SkeletonTheme } from 'react-loading-skeleton'
import 'react-loading-skeleton/dist/skeleton.css'
import './globals.css'

const montserrat = Montserrat({
	weight: ['100', '200', '300', '400', '500', '600', '800'],
	subsets: ['latin'],
	fallback: ['Arial', 'sans-serif'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={montserrat.className}>
			<SkeletonTheme baseColor='#b1b1b1' highlightColor='#e0e0e0'>
				<body className={`antialiased`}>{children}</body>
			</SkeletonTheme>
		</html>
	)
}
