import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { ReactNode } from 'react'
import { SkeletonTheme } from 'react-loading-skeleton'
import 'react-loading-skeleton/dist/skeleton.css'
import './globals.css'
import { ReduxProvider } from './redux/provider'

const montserrat = Montserrat({
	weight: ['100', '200', '300', '400', '500', '600', '800'],
	subsets: ['latin'],
	fallback: ['Arial', 'sans-serif'],
})

export const metadata: Metadata = {
	title: 'EWSEEWVA Shop',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{ children: ReactNode }>) {
	const bodyBuilder = () => {
		return (
			<SkeletonTheme baseColor='#b1b1b1' highlightColor='#e0e0e0'>
				<body id='body' className={`antialiased`}>
					{children}
				</body>
				<div id='web-portal'></div>
			</SkeletonTheme>
		)
	}
	return (
		<html lang='en' className={montserrat.className}>
			<ReduxProvider>{bodyBuilder()}</ReduxProvider>
		</html>
	)
}
